steps:
# This step copies deployment script and runs it
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
    set -x && \
    chmod +x deployment.sh && \
    export PROJECT_ID && \
    echo $PROJECT_ID && \
    export DEPLOYMENT_ID="label-testing" && \
    ./deployment.sh
